CREATE TABLE IF NOT EXISTS AssetSourceCredentials (
  ID     INT PRIMARY KEY AUTO_INCREMENT,
  Name   VARCHAR(255) NOT NULL,
  User   VARCHAR(255) NOT NULL,
  Key    VARCHAR(255),
  Secret VARCHAR(255)
);
