CREATE TABLE IF NOT EXISTS AssetSourceCredentials (
  ID     INT PRIMARY KEY AUTO_INCREMENT,
  Type   VARCHAR(255) NOT NULL,
  User   VARCHAR(255),
  Key    VARCHAR(255),
  Secret VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OfflineAccounts (
  ID      INT PRIMARY KEY AUTO_INCREMENT,
  Name    VARCHAR(255) NOT NULL,
  Balance DECIMAL      NOT NULL
);
